CREATE TABLE IF NOT EXISTS "Patients" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"dob" DATE NOT NULL,
	"mobile" INTEGER,
	"email" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Doctors" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"specialization" VARCHAR(255),
	"medical_license_no" INTEGER NOT NULL,
	"mobile" INTEGER,
	"email" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Appointments" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"doctor_id" INTEGER NOT NULL,
	"patient_id" INTEGER NOT NULL,
	"date" DATE NOT NULL,
	"time" TIME NOT NULL,
	"reason" VARCHAR(255),
	"status" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Treatments" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"description" VARCHAR(255),
	"cost" INTEGER,
	"duration" INTERVAL,
	"ward_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Wards" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"type" VARCHAR(255) NOT NULL DEFAULT 'General',
	"capacity" INTEGER,
	-- how many beds are available
	"available_beds" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "Wards"."available_beds" IS 'how many beds are available';


CREATE TABLE IF NOT EXISTS "Medical_records" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"doctor_id" INTEGER NOT NULL,
	"patient_id" INTEGER NOT NULL,
	"date" DATE NOT NULL DEFAULT 'today''s date',
	"diagnosis" VARCHAR(255),
	"notes" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "insurance_details" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"patient_id" INTEGER NOT NULL,
	"provider_name" VARCHAR(255) NOT NULL,
	"policy_type" VARCHAR(255),
	"start_date" DATE NOT NULL,
	"end_date" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Follow-up" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- referral can be a doctor itseft who is referring patient to some other doctor 
	"prev_appointment_id" INTEGER,
	"new_appointment_id" INTEGER NOT NULL,
	"referring_doctor_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "Follow-up"."prev_appointment_id" IS 'referral can be a doctor itseft who is referring patient to some other doctor ';


CREATE TABLE IF NOT EXISTS "sub_specialization" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"doctor_id" INTEGER,
	"specialization" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Treatment_by" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"treament_id" INTEGER,
	"doctor_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Lab_results" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"record_id" INTEGER,
	"test_name" VARCHAR(255),
	"result_value" INTEGER,
	"unit" INTEGER,
	"result_date" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Imaging_results" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"record_id" INTEGER,
	"imaging_type" VARCHAR(255),
	"report_summary" VARCHAR(255),
	"image_url" VARCHAR(255),
	"report_date" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "prescription_details" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"treatment_id" INTEGER,
	"record_id" INTEGER,
	"dosage" DECIMAL,
	"frequency" INTEGER,
	"duraction" INTERVAL,
	PRIMARY KEY("id")
);



ALTER TABLE "Patients"
ADD FOREIGN KEY("id") REFERENCES "insurance_details"("patient_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Patients"
ADD FOREIGN KEY("id") REFERENCES "Appointments"("patient_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Doctors"
ADD FOREIGN KEY("id") REFERENCES "Appointments"("doctor_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Appointments"
ADD FOREIGN KEY("id") REFERENCES "Follow-up"("prev_appointment_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Appointments"
ADD FOREIGN KEY("id") REFERENCES "Follow-up"("new_appointment_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Doctors"
ADD FOREIGN KEY("id") REFERENCES "Treatment_by"("doctor_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Wards"
ADD FOREIGN KEY("id") REFERENCES "Treatments"("ward_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Treatments"
ADD FOREIGN KEY("id") REFERENCES "Treatment_by"("treament_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Doctors"
ADD FOREIGN KEY("id") REFERENCES "sub_specialization"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Medical_records"
ADD FOREIGN KEY("id") REFERENCES "prescription_details"("record_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Medical_records"
ADD FOREIGN KEY("id") REFERENCES "Imaging_results"("record_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Medical_records"
ADD FOREIGN KEY("id") REFERENCES "Lab_results"("record_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Doctors"
ADD FOREIGN KEY("id") REFERENCES "Medical_records"("doctor_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Patients"
ADD FOREIGN KEY("id") REFERENCES "Medical_records"("patient_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Treatments"
ADD FOREIGN KEY("id") REFERENCES "prescription_details"("treatment_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;