CREATE TABLE IF NOT EXISTS "books" (
	-- International Standard Book Number
	"ISBN" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"title" VARCHAR(255) NOT NULL,
	"Publication_year" TIME NOT NULL,
	"edition" INTEGER,
	"genre" VARCHAR(255),
	"isAvailable_eBook" BOOLEAN,
	"isAvailable_hardCover" BOOLEAN,
	PRIMARY KEY("ISBN")
);


COMMENT ON COLUMN "books"."ISBN" IS 'International Standard Book Number';


CREATE TABLE IF NOT EXISTS "members" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	-- type can be:
	-- regular or premium
	"membership_type" VARCHAR(255),
	"mobile" INTEGER,
	"email" VARCHAR(255),
	"" ,
	PRIMARY KEY("id")
) INHERITS ("Contact details");


COMMENT ON COLUMN "members"."membership_type" IS 'type can be:
regular or premium';


CREATE TABLE IF NOT EXISTS "authors" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"nationality" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "publishers" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"mobile" INTEGER,
	"email" VARCHAR(255),
	PRIMARY KEY("id")
) INHERITS ("Contact details");




CREATE TABLE IF NOT EXISTS "library_branches" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"location" VARCHAR(255),
	"mobile" INTEGER,
	"email" VARCHAR(255),
	PRIMARY KEY("id")
) INHERITS ("Contact details");




CREATE TABLE IF NOT EXISTS "book_copies" (
	"book_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"copy_id" INTEGER NOT NULL,
	PRIMARY KEY("copy_id")
) INHERITS ("books");

COMMENT ON TABLE "book_copies" IS 'Composite key: <book_id, copy_id> 
as diff books might have same copy_id
';


CREATE TABLE IF NOT EXISTS "borrow_history" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"book_copy_id" INTEGER NOT NULL,
	"member_id" INTEGER NOT NULL,
	"borrow_date" DATE NOT NULL,
	"due_date" DATE NOT NULL,
	-- if the return date is after the due date,
	-- calculate the late fine
	"return_date" DATE NOT NULL,
	"condition" VARCHAR(255),
	"Fine" MONEY,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "borrow_history"."return_date" IS 'if the return date is after the due date,
calculate the late fine';


CREATE TABLE IF NOT EXISTS "isWrittenBy" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"contract_id" INTEGER,
	"book_id" INTEGER NOT NULL,
	"author_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "isWrittenBy" IS 'Composite key: <book_id, author_id>';


CREATE TABLE IF NOT EXISTS "Contract" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"publisher_id" INTEGER NOT NULL,
	"book_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "Contract" IS 'id is contract id';


CREATE TABLE IF NOT EXISTS "discount" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"branch_id" INTEGER NOT NULL,
	"publisher_id" INTEGER NOT NULL,
	"book_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	"discount" DECIMAL CHECK(0<=discount<=100),
	PRIMARY KEY("id")
) INHERITS ("publishers", "library_branches");

COMMENT ON TABLE "discount" IS 'discount is in percentage
';


CREATE TABLE IF NOT EXISTS "Inventory" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"book_id" INTEGER NOT NULL,
	"copy_id" INTEGER NOT NULL,
	"branch_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "reservation" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"book_id" INTEGER NOT NULL,
	"member_id" INTEGER NOT NULL,
	"reservation_date" DATE NOT NULL,
	"expiration_date" DATE NOT NULL,
	"notification_status" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("members");



ALTER TABLE "members"
ADD FOREIGN KEY("id") REFERENCES "reservation"("member_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "members"
ADD FOREIGN KEY("id") REFERENCES "borrow_history"("member_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "book_copies"
ADD FOREIGN KEY("copy_id") REFERENCES "borrow_history"("book_copy_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "library_branches"
ADD FOREIGN KEY("id") REFERENCES "Inventory"("branch_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "authors"
ADD FOREIGN KEY("id") REFERENCES "isWrittenBy"("author_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "publishers"
ADD FOREIGN KEY("id") REFERENCES "Contract"("publisher_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "publishers"
ADD FOREIGN KEY("id") REFERENCES "discount"("publisher_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "books"
ADD FOREIGN KEY("ISBN") REFERENCES "Contract"("book_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "books"
ADD FOREIGN KEY("ISBN") REFERENCES "reservation"("book_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "library_branches"
ADD FOREIGN KEY("id") REFERENCES "discount"("branch_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "book_copies"
ADD FOREIGN KEY("copy_id") REFERENCES "Inventory"("copy_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "books"
ADD FOREIGN KEY("ISBN") REFERENCES "Inventory"("book_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "books"
ADD FOREIGN KEY("ISBN") REFERENCES "book_copies"("book_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;