CREATE TABLE IF NOT EXISTS "Organization" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Organization_membership" (
	-- Id is foreign key from users table
	-- 
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- org-id is foreign key from organization table
	"org_id" INTEGER NOT NULL,
	"pos_id" INTEGER,
	-- it can be:
	-- Full time,
	-- Part time,
	-- Follower
	"membership" VARCHAR(255)
) INHERITS ("Users", "Organization");

COMMENT ON TABLE "Organization_membership" IS 'Composite Key: < user_id, org_id >';
COMMENT ON COLUMN "Organization_membership"."user_id" IS 'Id is foreign key from users table
';
COMMENT ON COLUMN "Organization_membership"."org_id" IS 'org-id is foreign key from organization table';
COMMENT ON COLUMN "Organization_membership"."membership" IS 'it can be:
Full time,
Part time,
Follower';


CREATE TABLE IF NOT EXISTS "Position" (
	"pos_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"position" VARCHAR(255) NOT NULL,
	"org_id" INTEGER NOT NULL,
	-- if this is 0 meaning that this position is vacant
	"no_of_users" INTEGER NOT NULL,
	PRIMARY KEY("pos_id")
) INHERITS ("Organization");

COMMENT ON TABLE "Position" IS 'Contains all positions in organizations, 
it is a weak entity depending on organization';
COMMENT ON COLUMN "Position"."no_of_users" IS 'if this is 0 meaning that this position is vacant';


CREATE TABLE IF NOT EXISTS "Org-tree" (
	"org_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"pos_id" INTEGER NOT NULL CHECK(IF position = Founder, then par_position = NULL),
	"par_pos_id" INTEGER CHECK(IF position = Founder, then par_position = NULL)
) INHERITS ("Organization", "Position");

COMMENT ON TABLE "Org-tree" IS 'organization tree has position and par position from Position table ';


CREATE TABLE IF NOT EXISTS "Connections" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- it can be user or organization
	"type_of_reciever" VARCHAR(255) NOT NULL,
	"id_of_reciever" INTEGER NOT NULL,
	-- Connection type can be:
	-- full-time,
	-- part-time,
	-- follower
	"type" VARCHAR(255) NOT NULL
) INHERITS ("Users", "Organization", "isEmployeeIn");


COMMENT ON COLUMN "Connections"."type_of_reciever" IS 'it can be user or organization';
COMMENT ON COLUMN "Connections"."type" IS 'Connection type can be:
full-time,
part-time,
follower';


CREATE TABLE IF NOT EXISTS "Request_history" (
	"req_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"sent_by" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- it can be user or organization
	"type_of_reciever" VARCHAR(255) NOT NULL,
	"id_of_reciever" INTEGER NOT NULL,
	-- status can be: 
	-- Pending 
	-- Approved 
	-- Rejected 
	"status" VARCHAR(255) NOT NULL,
	-- request type can be: 
	-- to join an organization 
	-- 
	-- To movement within an Org Tree 
	-- 
	-- to creation or modification of positions (if permitted) 
	"type" VARCHAR(255) NOT NULL,
	"description" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("req_id")
) INHERITS ("Users", "Organization");


COMMENT ON COLUMN "Request_history"."type_of_reciever" IS 'it can be user or organization';
COMMENT ON COLUMN "Request_history"."status" IS 'status can be: 
Pending 
Approved 
Rejected ';
COMMENT ON COLUMN "Request_history"."type" IS 'request type can be: 
to join an organization 

To movement within an Org Tree 

to creation or modification of positions (if permitted) ';


CREATE TABLE IF NOT EXISTS "Users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Username" VARCHAR(255) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"created_at" TIMESTAMP NOT NULL,
	"modified_at" TIMESTAMP NOT NULL,
	"bio" VARCHAR(255),
	PRIMARY KEY("id")
);



ALTER TABLE "Users"
ADD FOREIGN KEY("id") REFERENCES "Organization_membership"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Users"
ADD FOREIGN KEY("id") REFERENCES "Request_history"("sent_by")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Organization"
ADD FOREIGN KEY("id") REFERENCES "Organization_membership"("org_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Organization"
ADD FOREIGN KEY("id") REFERENCES "Position"("org_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Organization"
ADD FOREIGN KEY("id") REFERENCES "Org-tree"("org_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Position"
ADD FOREIGN KEY("position") REFERENCES "Org-tree"("pos_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Position"
ADD FOREIGN KEY("position") REFERENCES "Org-tree"("par_pos_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Users"
ADD FOREIGN KEY("id") REFERENCES "Connections"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Position"
ADD FOREIGN KEY("position") REFERENCES "Organization_membership"("pos_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Users"
ADD FOREIGN KEY("id") REFERENCES "Request_history"("id_of_reciever")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Organization"
ADD FOREIGN KEY("id") REFERENCES "Request_history"("id_of_reciever")
ON UPDATE NO ACTION ON DELETE NO ACTION;